domain: search-companion.org
url: https://www.search-companion.org
google_analytics:
baseurl: /
theme: jekyll-theme-slate
title: search-companion
description: Home for the Solr search companion. Search-companion simplifies daily interactions with Solr.
